### ISSUE TITLE
Not all admin log entries will be dumped to Sumo

### ISSUE THREAD

**Issue by SpencerBales** [ankitgoelcmu/SumoLogic-Duo-Lambda-Function#3]
If more than one admin log entry is created in the scan interval you will only get one of them written to Sumo because line 73 and 74 in the lambda_function.py file are indented one indentation too far. This places them inside the "for" loop which re-writes the "data" variable and stops the loop since the other items that were previously in the "data" variable have now been over-written.

**Comment by ankitgoelcmu** [comment]
Thanks for reporting, I will fix it soon
